name: deploy

#on:
#  registry_package:
#    types: [published, updated]
#    package_type: container

on:
  repository_dispatch:
    types: [package_published]

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Echo image tag
        run: |
          PACKAGE="${{ github.event.client_payload.package }}"
          echo ${PACKAGE}
          # Extract the tag from the event
          # IMAGE_TAG="${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          # echo ${IMAGE_TAG}
